### ISSUE TITLE
git mirrors causing sshd to hang?

### ISSUE THREAD

**Issue by logicminds** [samrocketman/gitlab-mirrors#89] opened 2015-11-18 17:50 UTC
I am not completely sure if this project is the cause of sshd hanging, but if others are experiencing a similar issue we might have to look into this issue.

My environment consists of around 60 repos being synced every 30 minutes via gitlab_mirrors scripts.  About every two weeks or so our gitlab server becomes extremely slow and unresponsive which could be caused by constant syncing and leaving ssh sessions in a bad state.  We usually just kill off the ssh connections and things go back to normal but it would be great to not have to do this.  I am probably the extreme case here but curious what others are up to.

Is anyone else experiencing this issue?

@cdenneen

**Comment by logicminds** [comment] 2015-11-18 17:51
I should also mention that we are syncing with gitlab.com which can be slow sometimes.

**Comment by samrocketman** [comment] 2015-11-19 06:25
As far as I know it loops over each project serially.  There shouldn't be more than one repository being synced at a time.  Since that's the case I'm not sure how this would be the cause of sshd to hang.  It uses normal git transports to sync via SSH so if git is your problem perhaps file a bug with the upstream project?  You'll probably be asked to provide more investigation in the upstream bug report.

How many users are on your system?

**Comment by cdenneen** [comment] 2015-11-19 16:00
@logicminds I haven't experienced this yet but I'm running gitlab locally so maybe it's an issue with gitlab.com?

**Comment by samrocketman** [comment] 2017-11-03 23:48
I'm closing this since there hasn't been any activity and it doesn't look like there's been any new reports on it.  Please open a new issue if this problem persists and link back to this one.

**Closed by samrocketman** 2017-11-03 23:48 UTC
Labels: feedback needed
